<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="testMenu.aspx.cs" Inherits="testMenu" %>

<%@ Register Assembly="Infragistics2.WebUI.WebCombo.v8.2, Version=8.2.20082.1000, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb"
    Namespace="Infragistics.WebUI.WebCombo" TagPrefix="igcmbo" %>

<%@ Register Assembly="Infragistics2.WebUI.UltraWebNavigator.v8.2, Version=8.2.20082.1000, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb"
    Namespace="Infragistics.WebUI.UltraWebNavigator" TagPrefix="ignav" %>

<%@ Register assembly="Infragistics2.WebUI.UltraWebToolbar.v8.2, Version=8.2.20082.1000, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" namespace="Infragistics.WebUI.UltraWebToolbar" tagprefix="igtbar" %>

<%@ Register assembly="System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" namespace="System.Web.UI" tagprefix="cc1" %>

<%@ Register assembly="Infragistics2.WebUI.UltraWebGrid.v8.2, Version=8.2.20082.1000, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb" namespace="Infragistics.WebUI.UltraWebGrid" tagprefix="igtbl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div style="width:900px;">
<ul id="nav">
				<li class="top"><a href="#nogo1" class="top_link"><span class="down">دراسات</span></a>
				<ul class="sub">
			<li>
			<asp:HyperLink runat="server" ID="default" NavigateUrl="~/Default.aspx">عرض/بحث دراسة</asp:HyperLink>
			</li>
			<li><asp:HyperLink ID="insertdata" NavigateUrl="~/Members/Insertdata.aspx" runat="server">إدخال دراسة</asp:HyperLink></li>
			
			</ul>
</li>
	<li class="top"><a href="#nogo2" id="products" class="top_link"><span class="down">قرارات</span></a>
		<ul class="sub">
			<li>
			<asp:HyperLink runat="server" ID="decSearch" NavigateUrl="~/testDecData.aspx?id=1">إجراءات عمل</asp:HyperLink>
			</li>
			<li>
			<asp:HyperLink runat="server" ID="insertDec" NavigateUrl="~/testDecData.aspx?id=2">
			شئون عاملين
			</asp:HyperLink>
			</li>
			<li>
			<asp:HyperLink runat="server" ID="HyperLink1" NavigateUrl="~/testDecData.aspx?id=3">
			لجان
			</asp:HyperLink>
			</li>
			</ul>
			</li>
			</ul>	
        
        <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
            ContextTypeName="testClassesDataContext" EnableInsert="True" 
            EnableUpdate="True" TableName="industrialSectors" EnableDelete="True" 
            Select="new (SectorName, ClassID)">
        </asp:LinqDataSource>
        <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            AutoGenerateInsertButton="True" AutoGenerateRows="False" 
            DataSourceID="LinqDataSource1">
            <Fields>
                <asp:BoundField DataField="SectorName" HeaderText="SectorName" ReadOnly="True" 
                    SortExpression="SectorName" />
                <asp:BoundField DataField="ClassID" HeaderText="ClassID" ReadOnly="True" 
                    SortExpression="ClassID" />
            </Fields>
        </asp:DetailsView>
    </div>
  
    <asp:SqlDataSource ID="ssssssssssssss" runat="server" 
        ConnectionString="<%$ ConnectionStrings:dataBankConnectionString %>" 
        SelectCommand="SELECT [decTypeID], [decType] FROM [decision_Types]">
    </asp:SqlDataSource>
  
</asp:Content>


